insert into Teams (Id, Name, Img)
Values (NEWID(), 'Alemanha', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Alemanha.svg'),
(NEWID(), 'Argentina', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Argentina.svg'),
(NEWID(), 'Arábia Saudita', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Ar%C3%A1bia_Saudita.svg'),
(NEWID(), 'Austrália', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Australia.svg'),
(NEWID(), 'Brasil', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Brasil.svg'),
(NEWID(), 'Bélgica', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/B%C3%A9lgica.svg'),
(NEWID(), 'Camarões', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Camar%C3%B5es.svg'),
(NEWID(), 'Canadá', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Canad%C3%A1.svg'),
(NEWID(), 'Catar', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Catar.svg'),
(NEWID(), 'Coreia do Sul', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Coreia_do_Sul.svg'),
(NEWID(), 'Costa Rica', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Costa_Rica.svg'),
(NEWID(), 'Croácia', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Cro%C3%A1cia.svg'),
(NEWID(), 'Dinamarca', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Dinamarca.svg'),
(NEWID(), 'Equador', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Equador.svg'),
(NEWID(), 'Espanha', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Espanha.svg'),
(NEWID(), 'Estados Unidos', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Estados_Unidos.svg'),
(NEWID(), 'França', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Fran%C3%A7a.svg'),
(NEWID(), 'Gana', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Gana.svg'),
(NEWID(), 'Holanda', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Holanda.svg'),
(NEWID(), 'Inglaterra', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Inglaterra.svg'),
(NEWID(), 'Irã', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Ir%C3%A3.svg'),
(NEWID(), 'Japão', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Japao.svg'),
(NEWID(), 'Marrocos', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Marrocos.svg'),
(NEWID(), 'México', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/M%C3%A9xico.svg'),
(NEWID(), 'País de Gales', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Pa%C3%ADs_de_Gales.svg'),
(NEWID(), 'Polônia', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Polonia.svg'),
(NEWID(), 'Portugal', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Portugal.svg'),
(NEWID(), 'Senegal', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Senegal.svg'),
(NEWID(), 'Sérvia', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Servia.svg'),
(NEWID(), 'Suíça', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Su%C3%AD%C3%A7a.svg'),
(NEWID(), 'Tunísia', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Tunisia.svg'),
(NEWID(), 'Uruguai ', 'https://raw.githubusercontent.com/Code-Yourself-Oficial/world-cup-simulator-files/main/teams/Uruguai.svg')